model: stabilityai/stable-diffusion-xl-base-1.0

modelParameters:
  pipeline: diffusion

inference:
  serviceName: sd-diffusers
  serviceNamespace: default
  accelerator: gpu
  framework: diffusers

  modelServer:
    image:
      repository: docker-registry.selectel.ru/diffusers/diffusers-pytorch-cuda
      tag: latest
    deployment:
      instanceType: GL14.12-65536-1GPU
