apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-dns-selectel.fullname" . }}
  labels:
    app.kubernetes.io/name: external-dns-selectel
    app.kubernetes.io/instance: {{ .Release.Name }}
